apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-stage
  labels:
    app: express-stage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: express-stage
    name: in-cluster
  project: express
  source:
    path: ./k8s-resources/express/overlays/stage
    repoURL: https://github.com/TedSpinks/gitops-demo.git
    targetRevision: openshift
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true      