apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express-microservice
spec:
  replicas: 4
  revisionHistoryLimit: 3 
  selector:
    matchLabels:
      app: express-microservice
  template:
    metadata:
      labels:
        app: express-microservice
    spec:
      containers:
        - name: express-microservice
          image: quay.io/tedspinks/express:8b1592d
          ports:
            - containerPort: 3000
      imagePullSecrets:
      - name: quay-regcred
  minReadySeconds: 30
  strategy:
    canary:
#       stableService: express-active
#       canaryService: express-preview
#       trafficRouting:
#         nginx:
#           stableIngress: express-stable-ingress
      analysis:
        templates:
        - templateName: pass-always
        - templateName: mixed-tests
        startingStep: 1
      steps:
        - setWeight: 25
        - pause: {duration: 1m}
